/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ozyvmadobfguigmbpbwh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96eXZtYWRvYmZndWlnbWJwYndoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYxMjY3NDcsImV4cCI6MjA4MTcwMjc0N30._fer1zavFKvZ67DLKg0cuKC-85FX7-8mlv8ihgGl3gA"